import Layout from "@/components/layout"
import { UserProvider } from '../contexts/userContext'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider> 
          <Layout>{children}</Layout> 
        </UserProvider>
      </body>  
    </html>
  )
}
